import React, { useEffect, useState } from 'react';
import { CustomerRow } from '../types';
import { User, Phone, Contact, X, Check, Search } from 'lucide-react';

interface CustomerDialogProps { list: CustomerRow[]; current: string; currentPhone: string; onSave: (name: string, phone: string) => void; onClose: () => void; }

export const CustomerDialog: React.FC<CustomerDialogProps> = ({ list, current, currentPhone, onSave, onClose }) => {
  const [name, setName] = useState(current === 'عميل نقدي' ? '' : current);
  const [phone, setPhone] = useState(currentPhone);
  const [filter, setFilter] = useState('');
  useEffect(() => { (window as any).__aziziOnContactPicked = (pickedName: string, pickedPhone: string) => { setName(pickedName || ''); setPhone((pickedPhone || '').replace(/\s+/g, '')); }; return () => { delete (window as any).__aziziOnContactPicked; }; }, []);
  const filteredList = list.filter(c => c.name.toLowerCase().includes(filter.toLowerCase()) || c.phone.includes(filter));
  const handlePickContact = () => { const native = (window as any).AndroidAzizi; if (native?.pickContact) { native.pickContact(); return; } if ('contacts' in navigator && 'ContactsManager' in window) { (navigator as any).contacts.select(['name','tel'], {multiple:false}).then((contacts:any[]) => { if (contacts?.length) { if (contacts[0].name?.length) setName(contacts[0].name[0]); if (contacts[0].tel?.length) setPhone(contacts[0].tel[0].replace(/\s+/g,'')); } }).catch(() => {}); } else alert('اختيار جهات الاتصال متاح داخل تطبيق Android. يرجى استخدام نسخة APK.'); };
  const handleSave = () => { const clean = name.trim(); if (!clean) { alert('يرجى كتابة اسم العميل'); return; } onSave(clean, phone.trim()); };
  return (<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-xs animate-fadeIn"><div className="bg-white dark:bg-slate-800 rounded-2xl w-full max-w-md shadow-xl border border-slate-200 dark:border-slate-700 overflow-hidden flex flex-col max-h-[90vh]"><div className="p-4 border-b flex items-center justify-between"><h3 className="font-bold text-base flex items-center gap-2"><User className="w-5 h-5 text-blue-700" />{current && current !== 'عميل نقدي' ? 'تعديل أو اختيار العميل' : 'إضافة أو اختيار عميل'}</h3><button onClick={onClose} className="p-1"><X className="w-5 h-5" /></button></div><div className="p-4 overflow-y-auto space-y-3.5 flex-1"><button type="button" onClick={handlePickContact} className="w-full flex items-center justify-center gap-2 py-2 px-3 rounded-xl border text-xs font-medium"><Contact className="w-4 h-4 text-blue-600" />اختيار من جهات الاتصال</button><div><label className="block text-xs font-semibold mb-1">اسم العميل <span className="text-red-500">*</span></label><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="أدخل اسم العميل" className="w-full px-3 py-2 text-sm bg-slate-50 border rounded-xl" /></div><div><label className="block text-xs font-semibold mb-1">رقم الجوال / واتساب</label><input type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="مثلاً: 777123456" className="w-full px-3 py-2 text-sm bg-slate-50 border rounded-xl" /></div>{list.length>0&&<div className="pt-2 border-t"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold">العملاء المحفوظون ({list.length})</span><div className="relative w-36"><input type="text" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="بحث..." className="w-full px-2 py-0.5 text-xs border rounded-lg" /><Search className="w-3 h-3 absolute right-2 top-1.5 text-slate-400" /></div></div><div className="max-h-40 overflow-y-auto">{filteredList.map(c=><button key={c.id} type="button" onClick={()=>{setName(c.name);setPhone(c.phone);}} className="w-full text-right py-1.5 px-2 rounded-lg flex items-center justify-between"><div><div className="text-xs font-semibold">{c.name}</div><div className="text-[10px] text-slate-400">{c.phone||'بدون جوال'}</div></div>{c.balance>0&&<span className="text-[10px] text-red-600">دين: {c.balance} ر.ي</span>}</button>)}</div></div>}</div><div className="p-3 border-t flex items-center justify-end gap-2"><button type="button" onClick={onClose} className="px-4 py-2 text-xs rounded-xl">إلغاء</button><button type="button" onClick={handleSave} className="px-4 py-2 text-xs font-bold text-white bg-blue-700 rounded-xl flex items-center gap-1.5"><Check className="w-4 h-4" />حفظ واختيار العميل</button></div></div></div>);
};